name: Local
variables:
  - name: BASE_URL
    value: http://localhost:8080
  - secret: true
    name: AUTH_TOKEN
    description: ""
  - secret: true
    name: INVITE_TOKEN
    description: ""
  - secret: true
    name: _EMAIL
    description: ""
  - secret: true
    name: _PWD
    description: ""
  - secret: true
    name: EMAIL
    description: ""
  - secret: true
    name: PWD
    description: ""
