name: Local
variables:
  - name: BASE_URL
    value: http://localhost:8080
  - secret: true
    name: AUTH_TOKEN
  - secret: true
    name: INVITE_TOKEN
  - secret: true
    name: _EMAIL
  - secret: true
    name: _PWD
  - secret: true
    name: EMAIL
  - secret: true
    name: PWD
